# Generated by Django 4.0.2 on 2022-08-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshop',
            name='budget',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='bookshop',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
