# Generated by Django 4.0.2 on 2022-08-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_bookshop_budget_bookshop_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshop',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='bookshop',
            name='year',
        ),
        migrations.AddField(
            model_name='bookshop',
            name='is_best_seller',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
