# Generated by Django 4.0.2 on 2022-08-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_bookshop_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshop',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
